/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersWsRouteImport } from './routes/users-ws'
import { Route as LaundromatRouteImport } from './routes/laundromat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsersWsRoute = UsersWsRouteImport.update({
  id: '/users-ws',
  path: '/users-ws',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundromatRoute = LaundromatRouteImport.update({
  id: '/laundromat',
  path: '/laundromat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/laundromat': typeof LaundromatRoute
  '/users-ws': typeof UsersWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/laundromat': typeof LaundromatRoute
  '/users-ws': typeof UsersWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/laundromat': typeof LaundromatRoute
  '/users-ws': typeof UsersWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/admin' | '/laundromat' | '/users-ws'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/admin' | '/laundromat' | '/users-ws'
  id: '__root__' | '/' | '/about' | '/admin' | '/laundromat' | '/users-ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  LaundromatRoute: typeof LaundromatRoute
  UsersWsRoute: typeof UsersWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users-ws': {
      id: '/users-ws'
      path: '/users-ws'
      fullPath: '/users-ws'
      preLoaderRoute: typeof UsersWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundromat': {
      id: '/laundromat'
      path: '/laundromat'
      fullPath: '/laundromat'
      preLoaderRoute: typeof LaundromatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  LaundromatRoute: LaundromatRoute,
  UsersWsRoute: UsersWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
